---
name: "Palco"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "0.1.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "j4ckgrey"
artifacts:
  - "Palco.dll"
overview: "Minimal cache for Anfiteatro"
description: >
  Minimal cache for Anfiteatro with catalog import support.
category: "General"
changelog: >
  Fix plugin update process by adopting JPRM build system
